export const TITLES =
[
  { "id": "squid-game", "title": "오징어 게임", "contentClass": "k-drama" },
  { "id": "the-glory", "title": "더 글로리", "contentClass": "k-drama" },
  { "id": "kingdom", "title": "킹덤", "contentClass": "k-drama" },
  { "id": "parasite", "title": "기생충", "contentClass": "k-movie" },
  { "id": "train-to-busan", "title": "부산행", "contentClass": "k-movie" },
  { "id": "oldboy", "title": "올드보이", "contentClass": "k-movie" },
  { "id": "the-handmaiden", "title": "아가씨", "contentClass": "k-movie" },
  { "id": "a-killer-paradox", "title": "살인자ㅇ난감", "contentClass": "k-drama" },
  { "id": "gyeongseong-creature", "title": "경성크리처", "contentClass": "k-drama" },
  { "id": "crash-landing-on-you", "title": "사랑의 불시착", "contentClass": "k-drama" },
  { "id": "itaewon-class", "title": "이태원 클라쓰", "contentClass": "k-drama" },
  { "id": "hospital-playlist", "title": "슬기로운 의사생활", "contentClass": "k-drama" },
  { "id": "vincenzo", "title": "빈센조", "contentClass": "k-drama" },
  { "id": "mr-sunshine", "title": "미스터 션샤인", "contentClass": "k-drama" },
  { "id": "signal", "title": "시그널", "contentClass": "k-drama" },
  { "id": "reply-1988", "title": "응답하라 1988", "contentClass": "k-drama" },
  { "id": "extraordinary-attorney-woo", "title": "이상한 변호사 우영우", "contentClass": "k-drama" },
  { "id": "my-name", "title": "마이 네임", "contentClass": "k-drama" },
  { "id": "all-of-us-are-dead", "title": "지금 우리 학교는", "contentClass": "k-drama" },
  { "id": "hellbound", "title": "지옥", "contentClass": "k-drama" },
  { "id": "dp", "title": "D.P.", "contentClass": "k-drama" },
  { "id": "sweet-home", "title": "스위트홈", "contentClass": "k-drama" },
  { "id": "the-call", "title": "콜", "contentClass": "k-movie" },
  { "id": "space-sweepers", "title": "승리호", "contentClass": "k-movie" },
  { "id": "unlocked", "title": "스마트폰을 떨어뜨렸을 뿐인데", "contentClass": "k-movie" },

  { "id": "stranger-things", "title": "기묘한 이야기", "contentClass": "us-series" },
  { "id": "the-witcher", "title": "위쳐", "contentClass": "us-series" },
  { "id": "money-heist", "title": "종이의 집", "contentClass": "series" },
  { "id": "narcos", "title": "나르코스", "contentClass": "us-series" },
  { "id": "black-mirror", "title": "블랙 미러", "contentClass": "uk-series" },
  { "id": "breaking-bad", "title": "브레이킹 배드", "contentClass": "us-series" },
  { "id": "queens-gambit", "title": "퀸스 갬빗", "contentClass": "us-series" },
  { "id": "bridgerton", "title": "브리저튼", "contentClass": "us-series" },
  { "id": "the-crown", "title": "더 크라운", "contentClass": "uk-series" },
  { "id": "sex-education", "title": "오티스의 비밀 상담소", "contentClass": "uk-series" },
  { "id": "wednesday", "title": "웬즈데이", "contentClass": "us-series" },
  { "id": "beef", "title": "성난 사람들", "contentClass": "us-series" },
  { "id": "one-piece-live-action", "title": "원피스 (실사)", "contentClass": "us-series" },
  { "id": "the-sandman", "title": "샌드맨", "contentClass": "us-series" },
  { "id": "avatar-the-last-airbender", "title": "아바타: 아앙의 전설", "contentClass": "us-series" },
  { "id": "the-umbrella-academy", "title": "엄브렐러 아카데미", "contentClass": "us-series" },

  { "id": "inception", "title": "인셉션", "contentClass": "movie" },
  { "id": "interstellar", "title": "인터스텔라", "contentClass": "movie" },
  { "id": "the-dark-knight", "title": "다크 나이트", "contentClass": "movie" },
  { "id": "joker", "title": "조커", "contentClass": "movie" },
  { "id": "dune", "title": "듄", "contentClass": "movie" },
  { "id": "everything-everywhere-all-at-once", "title": "에브리씽 에브리웨어 올 앳 원스", "contentClass": "movie" },
  { "id": "glass-onion", "title": "나이브스 아웃: 글래스 어니언", "contentClass": "movie" },
  { "id": "red-notice", "title": "레드 노티스", "contentClass": "movie" },
  { "id": "dont-look-up", "title": "돈 룩 업", "contentClass": "movie" },
  { "id": "the-gray-man", "title": "그레이 맨", "contentClass": "movie" },
  { "id": "roma", "title": "로마", "contentClass": "movie" },
  { "id": "the-irishman", "title": "아이리시맨", "contentClass": "movie" },
  { "id": "okja", "title": "옥자", "contentClass": "k-movie" },
  { "id": "enola-holmes", "title": "에놀라 홈즈", "contentClass": "movie" },

  { "id": "spirited-away", "title": "센과 치히로의 행방불명", "contentClass": "anime-movie" },
  { "id": "your-name", "title": "너의 이름은.", "contentClass": "anime-movie" },
  { "id": "howls-moving-castle", "title": "하울의 움직이는 성", "contentClass": "anime-movie" },
  { "id": "demon-slayer", "title": "귀멸의 칼날", "contentClass": "anime-series" },
  { "id": "attack-on-titan", "title": "진격의 거인", "contentClass": "anime-series" },
  { "id": "my-neighbor-totoro", "title": "이웃집 토토로", "contentClass": "anime-movie" },
  { "id": "jujutsu-kaisen", "title": "주술회전", "contentClass": "anime-series" },
  { "id": "spy-x-family", "title": "스파이 패밀리", "contentClass": "anime-series" },
  { "id": "chainsaw-man", "title": "체인소 맨", "contentClass": "anime-series" },
  { "id": "cyberpunk-edgerunners", "title": "사이버펑크: 엣지러너", "contentClass": "anime-series" },
  { "id": "arcane", "title": "아케인", "contentClass": "animation-series" },
  { "id": "suzume", "title": "스즈메의 문단속", "contentClass": "anime-movie" },

  { "id": "physical-100", "title": "피지컬: 100", "contentClass": "reality" },
  { "id": "singles-inferno", "title": "솔로지옥", "contentClass": "reality" },
  { "id": "the-devils-plan", "title": "데블스 플랜", "contentClass": "reality" },
  { "id": "i-am-solo", "title": "나는 SOLO", "contentClass": "reality" },
  { "id": "zombieverse", "title": "좀비버스", "contentClass": "reality" },
  { "id": "the-great-british-baking-show", "title": "그레이트 브리티시 베이킹 쇼", "contentClass": "reality" },
  { "id": "queer-eye", "title": "퀴어 아이", "contentClass": "reality" },

  { "id": "our-planet", "title": "우리의 지구", "contentClass": "documentary" },
  { "id": "the-last-dance", "title": "마이클 조던: 더 라스트 댄스", "contentClass": "documentary" },
  { "id": "making-a-murderer", "title": "살인자 만들기", "contentClass": "documentary" },
  { "id": "drive-to-survive", "title": "F1, 본능의 질주", "contentClass": "documentary" },
  { "id": "my-octopus-teacher", "title": "나의 문어 선생님", "contentClass": "documentary" },
  { "id": "the-tinder-swindler", "title": "티끌모아 로맨스", "contentClass": "documentary" },
  { "id": "in-the-name-of-god-a-holy-betrayal", "title": "나는 신이다: 신이 배신한 사람들", "contentClass": "documentary" },
  { "id": "sea-of-shadows", "title": "씨 오브 섀도우즈", "contentClass": "documentary" }
]